const ICONS = {
    HOME: require('../assets/icons/home.png'),
    HOME_ACTIVE: require('../assets/icons/home-active.png'),
    QUEUE: require('../assets/icons/queue.png'),
    QUEUE_ACTIVE: require('../assets/icons/queue-active.png'),
    PROFILE: require('../assets/icons/profile.png'),
    PROFILE_ACTIVE: require('../assets/icons/profile-active.png'),
    BOOK: require('../assets/icons/book.png'),
    FORWARD: require('../assets/icons/forward.png'),
    LINK: require('../assets/icons/link.png'),
    BROWSER: require('../assets/icons/browser.png'),
    AT: require('../assets/icons/at.png'),
    PRINT: require('../assets/icons/print.png'),
    EXPOPT: require('../assets/icons/export.png'),
    PLUS: require('../assets/icons/plus.png'),
    DOTS_THREE_CIRCLE: require('../assets/icons/dots-three-circle.png'),
    CLOSE_LIGHT: require('../assets/icons/close-light.png'),
    MOBILE: require('../assets/icons/mobile.png'),
    DESKTOP: require('../assets/icons/desktop.png'),
    CLOCK: require('../assets/icons/clock.png'),
    SORT: require('../assets/icons/sort.png'),
    FILTER: require('../assets/icons/filter.png'),
    EDIT: require('../assets/icons/edit.png'),
    FEEDBACK: require('../assets/icons/feedback.png'),
    PERSON: require('../assets/icons/person.png'),
    STAR: require('../assets/icons/star.png'),
    FILE_TRAY: require('../assets/icons/file-tray.png'),
    CHECK: require('../assets/icons/check.png'),
    ELLIPSE: require('../assets/icons/ellipse.png'),
    STARS: require('../assets/icons/stars.png'),
    HEADPHONES: require('../assets/icons/headphones.png'),
    NOTIFICATIONS: require('../assets/icons/notifications.png'),
    CHAT_BOX: require('../assets/icons/chatbox.png'),
    HEART: require('../assets/icons/heart.png'),
    PERSON_ADD: require('../assets/icons/person-add.png'),
    GMAIL: require('../assets/icons/gmail.png'),
    PHONE: require('../assets/icons/phone.png'),
    APPLE: require('../assets/icons/apple.png'),
    GOOGLE: require('../assets/icons/google.png'),
    FACEBOOK: require('../assets/icons/facebook.png'),
};

export default ICONS;